// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fivqvwlatipxbvcwoewc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpdnF2d2xhdGlweGJ2Y3dvZXdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NDU5NjMsImV4cCI6MjA2NTQyMTk2M30.j7Ik2Ztb5tvjoytuNQUdcB9tbm7HfIfbwai_qVWAFTw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);